import { useAppSelector } from '../store'

const translate: { en: Record<string, string>, hu: Record<string, string> } = {
  en: {
    'login.name': 'Username',
    'login.name.required': 'Username is required!',
    'login.password': 'Password',
    'login.password.required': 'Password is required!',
    'login.submit': 'Login',

    'register.name': 'Username',
    'register.name.required': 'Username is required!',
    'register.password': 'Password',
    'register.password.required': 'Password is required!',
    'register.email': 'Email',
    'register.email.required': 'Email is required!',
    'register.email.invalid': 'Email is invalid!',
    'register.submit': 'Register',

    'leaderboard.title': 'Leaderboard',
    'leaderboard.user.name': 'Name',
    'leaderboard.user.elo': 'Elo',
    'leaderboard.user.wins': 'Wins',
    'leaderboard.user.losses': 'Losses',
    'leaderboard.user.draws': 'Draws',
    'leaderboard.user.streak': 'Streak',

    'main.ongoing': 'Ongoing',
    'main.reconnect': 'Reconnect',
    'main.create': 'Create',
    'main.join': 'Join',
    'main.watch': 'Watch',
    'main.play': 'Play',

    'game.name': 'Name',
    'game.waiting': 'Waiting for opponent',
    'game.loading': 'Loading game',
    'game.notFound': 'Game not found',
    'game.your.turn': 'Your turn',
    'game.opponents.turn': 'Opponents turn',
    'game.white': 'White',
    'game.black': 'Black',
    'game.views': 'Views',
    'game.code': 'Code',
    'game.copy': 'Copy',
    'game.copied.title': 'Copied',
    'game.copied.message': 'Game link copied to clipboard',
    'game.rule.current': 'Current rule',
    'game.rule.next': 'Next rule',
    'game.rule.no-retreat': 'No retreat',
    'game.rule.no-capture': 'No capture',
    'game.rule.render-swap': 'Render swap',
    'game.rule.fog-of-war': 'Fog of war',
    'game.rule.no-pawns': 'No pawns',
    'game.rule.timeout': 'Timeout',
    'game.type': 'Type',
    'game.type.normal': 'Normal',
    'game.type.adaptive': 'Adaptive',
    'game.type.custom': 'Custom',

    'playdialog.title': 'Play',
    'playdialog.name': 'Lobby name',
    'playdialog.name.required': 'Lobby name is required!',
    'playdialog.public': 'Public',
    'playdialog.type': 'Type',
    'playdialog.time': 'Time',
    'playdialog.time.unlimited': 'Unlimited',
    'playdialog.time.minute': 'Minutes',
    'playdialog.fen': 'FEN',
    'playdialog.fen.invalid': 'Invalid FEN!',
    'playdialog.create': 'Create',

    'header.leaderboard': 'Leaderboard',
    'header.login': 'Login',
    'header.register': 'Register',
    'header.title': 'Adaptív Sakk',
    'header.darkmode': 'Dark mode',
    'header.lightmode': 'Light mode',

    'user.name': 'Name',
    'user.email': 'Email',
    'user.stats.elo': 'Elo',
    'user.stats.wins': 'Wins',
    'user.stats.losses': 'Losses',
    'user.stats.draws': 'Draws',
    'user.stats.streak': 'Streak',
  },
  hu: {
    'login.name': 'Felhasználónév',
    'login.name.required': 'Felhasználónév megadása kötelező!',
    'login.password': 'Jelszó',
    'login.password.required': 'Jelszó megadása kötelező!',
    'login.submit': 'Bejelentkezés',

    'register.name': 'Felhasználónév',
    'register.name.required': 'Felhasználónév megadása kötelező!',
    'register.password': 'Jelszó',
    'register.password.required': 'Jelszó megadása kötelező!',
    'register.email': 'Email',
    'register.email.required': 'Email megadása kötelező!',
    'register.email.invalid': 'Érvénytelen email cím!',
    'register.submit': 'Regisztráció',

    'leaderboard.title': 'Ranglista',
    'leaderboard.user.name': 'Név',
    'leaderboard.user.elo': 'Elo',
    'leaderboard.user.wins': 'Győzelmek',
    'leaderboard.user.losses': 'Vereségek',
    'leaderboard.user.draws': 'Döntetlenek',
    'leaderboard.user.streak': 'Sorozat',

    'main.ongoing': 'Folyamatban',
    'main.reconnect': 'Újracsatlakozás',
    'main.create': 'Létrehozás',
    'main.join': 'Csatlakozás',
    'main.watch': 'Megtekintés',
    'main.play': 'Játék',

    'game.name': 'Név',
    'game.waiting': 'Várakozás az ellenfélre',
    'game.loading': 'Betöltés, kérlek várj',
    'game.notFound': 'Játék nem található',
    'game.your.turn': 'Te következel',
    'game.opponents.turn': 'Ellenfél következik',
    'game.white': 'Fehér',
    'game.black': 'Fekete',
    'game.views': 'Nézők',
    'game.code': 'Kód',
    'game.copy': 'Másolás',
    'game.copied.title': 'Másolva',
    'game.copied.message': 'Játék link másolva a vágólapra',
    'game.rule.current': 'Jelenlegi szabály',
    'game.rule.next': 'Következő szabály',
    'game.rule.no-retreat': 'Nem vonulhat vissza',
    'game.rule.no-capture': 'Nincs ütés',
    'game.rule.render-swap': 'Átrendezés',
    'game.rule.fog-of-war': 'Háborús köd',
    'game.rule.no-pawns': 'Nincs gyalog',
    'game.rule.timeout': 'Szünet',
    'game.type': 'Típus',
    'game.type.normal': 'Normál',
    'game.type.adaptive': 'Adaptív',
    'game.type.custom': 'Egyedi',

    'playdialog.title': 'Játék',
    'playdialog.name': 'Szoba név',
    'playdialog.name.required': 'Szoba név megadása kötelező!',
    'playdialog.public': 'Nyilvános',
    'playdialog.time': 'Idő',
    'playdialog.time.unlimited': 'Korlátlan',
    'playdialog.time.minute': 'Perc',
    'playdialog.fen': 'FEN',
    'playdialog.fen.invalid': 'Érvénytelen FEN!',
    'playdialog.create': 'Létrehozás',

    'header.leaderboard': 'Ranglista',
    'header.login': 'Bejelentkezés',
    'header.register': 'Regisztráció',
    'header.title': 'Adaptív Sakk',
    'header.darkmode': 'Sötét mód',
    'header.lightmode': 'Világos mód',

    'user.name': 'Név',
    'user.email': 'Email',
    'user.stats.elo': 'Elo',
    'user.stats.wins': 'Győzelmek',
    'user.stats.losses': 'Vereségek',
    'user.stats.draws': 'Döntetlenek',
    'user.stats.streak': 'Sorozat',
  },
}

const useTranslate = () => {
  const language: 'en' | 'hu' = useAppSelector((state) => state.settings.language)
  return (key: string) => translate[language][key] ?? `UNDEFINED TRANSLATION: ${key}`
}

export default useTranslate
